version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  django:
    build: .
    # command: gunicorn revenue_forecasting.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
    depends_on:
      - db
    ports:
      - "8000:8000"

  nginx:
    image: nginx:1.19-alpine
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./revenue_forecasting/static:/app/static
    depends_on:
      - django
    ports:
      - "80:80"

volumes:
  postgres_data:
