# Generated by Django 4.2.5 on 2024-02-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetflixRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('global_revenue', models.BigIntegerField()),
                ('ucan_streaming_revenue', models.BigIntegerField()),
                ('emea_streaming_revenue', models.BigIntegerField()),
                ('latm_streaming_revenue', models.BigIntegerField()),
                ('apac_streaming_revenue', models.BigIntegerField()),
                ('ucan_members', models.IntegerField()),
                ('emea_members', models.IntegerField()),
                ('latm_members', models.IntegerField()),
                ('apac_members', models.IntegerField()),
                ('ucan_arpu', models.DecimalField(decimal_places=2, max_digits=5)),
                ('emea_arpu', models.DecimalField(decimal_places=2, max_digits=5)),
                ('latm_arpu', models.DecimalField(decimal_places=2, max_digits=5)),
                ('apac_arpu', models.DecimalField(decimal_places=2, max_digits=5)),
                ('netflix_streaming_memberships', models.BigIntegerField()),
            ],
        ),
    ]
